### PR TITLE
please review my PR, i added my resume.

### PR DESCRIPTION
**Pull request by jigneshsolanki07**

### CODE REVIEW

**Comment by avinash201199** [comment]
@shvam0000 check why this "all checks have failed " is showing ?

**Comment by shvam0000** [comment]
Sure, will look into it and fix ASAP

**Comment by shvam0000** [comment]
It seems that this is an issue not yet fixed by the GitHub actions itself. 
Refernce - https://github.com/actions/first-interaction/issues/10

It happens due to multiple reasons and only with a few rare actions.

**Comment by avinash201199** [comment]
> It seems that this is an issue not yet fixed by the GitHub actions itself. Refernce - [actions/first-interaction#10](https://github.com/actions/first-interaction/issues/10)
> 
> It happens due to multiple reasons and only with a few rare actions.

What to do now? Should I accept his pr by ignoring it?

**Comment by shvam0000** [comment]
Yes @avinash201199 this action has nothing to do with the quality of the PR.

**Comment by avinash201199** [comment]
> Yes @avinash201199 this action has nothing to do with the quality of the PR.

Okay :)

**Pull request merged**
